[tools]
rojo = "rojo-rbx/rojo@7.4.0"
lune = "lune-org/lune@0.8.0"
selene = "Kampfkarren/selene@0.26.1"
stylua = "JohnnyMorganz/StyLua@0.20.0"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "johnnymorganz/wally-package-types@1.3.1"
darklua = "seaofvoices/darklua@0.12.1"
tarmac = "rojo-rbx/tarmac@0.7.5"
rbxcloud = "sleitnick/rbxcloud@0.6.1"