[package]
name = "virtualbutfake/lucide-roblox"
version = "1.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "build",
    "build**",
    "LICENSE.md",
    "wally.toml",
    "default.project.json",
    "sourcemap.json",
]
exclude = ["*"]

[dependencies]
